[server]
baseUrlPath = ""

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2E4057"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#262730"
font = "sans serif" 